Fix compilation error introduced by previous changes:
program.cpp:39:7: error: conflicting declaration ‘ulong ProgramData::last_seq_stop_times [4]’
   39 | ulong ProgramData::last_seq_stop_times[NUM_SEQ_GROUPS];
      |       ^~~~~~~~~~~
In file included from program.cpp:25:
program.h:133:23: note: previous declaration as ‘time_t ProgramData::last_seq_stop_times []’
  133 |         static time_t last_seq_stop_times[]; // the last stop time of a sequential station (for each sequential group respectively)
      |                       ^~~~~~~~~~~~~~~~~~~